const DB="NovelReader";let db,S={v:"books"};const $=q=>document.querySelector(q),app=$("#app");const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+""+Math.random();const rq=r=>new Promise((a,b)=>{r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)});const st=(n,m="readonly")=>db.transaction(n,m).objectStore(n);const all=n=>rq(st(n).getAll());const get=(n,k)=>rq(st(n).get(k));const put=(n,x)=>rq(st(n,"readwrite").put(x));const del=(n,k)=>rq(st(n,"readwrite").delete(k));const ix=(n,i,k)=>rq(st(n).index(i).getAll(k));const esc=s=>(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function openDB(){return new Promise((a,b)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains("books"))d.createObjectStore("books",{keyPath:"id"});if(!d.objectStoreNames.contains("volumes")){let x=d.createObjectStore("volumes",{keyPath:"id"});x.createIndex("book","book")}if(!d.objectStoreNames.contains("chapters")){let x=d.createObjectStore("chapters",{keyPath:"id"});x.createIndex("volume","volume")}};r.onsuccess=()=>{db=r.result;a()};r.onerror=()=>b(r.error)})}
function head(t,s=""){ $("#title").textContent=t;$("#sub").textContent=s;$("#back").classList.toggle("hide",S.v==="books");$("#fab").classList.toggle("hide",["reader","form"].includes(S.v));$("#readerNav").classList.toggle("hide",S.v!=="reader")}
async function render(){if(S.v==="books")return books();if(S.v==="volumes")return volumes();if(S.v==="chapters")return chapters();if(S.v==="reader")return reader()}
async function books(){head("📚 本棚","端末内に保存");let a=await all("books");app.innerHTML=a.map(x=>`<div class=card onclick="openBook('${x.id}')"><h2>📖 ${esc(x.title)}</h2></div>`).join("")||"<div class=card>右下の＋から本を追加できます。</div>";app.innerHTML+=`<div class=card><div class=row><button class=secondary onclick=backup()>📤 バックアップ</button><button class=secondary onclick="$('#restore').click()">📥 復元</button></div></div>`}
window.openBook=i=>{S={v:"volumes",book:i};render()}
async function volumes(){let b=await get("books",S.book),a=await ix("volumes","book",S.book);head("📚 "+b.title,"巻を選択");app.innerHTML=a.map(x=>`<div class=card onclick="openVolume('${x.id}')"><h2>📕 ${esc(x.title)}</h2></div>`).join("")||"<div class=card>まだ巻がありません。</div>";app.innerHTML+=`<div class=card><div class=row><button onclick=addVolume()>＋ 巻追加</button><button class=danger onclick=deleteBook()>本を削除</button></div></div>`}
window.openVolume=i=>{S.v="chapters";S.volume=i;render()}
async function chapters(){let v=await get("volumes",S.volume),a=(await ix("chapters","volume",S.volume)).sort((x,y)=>x.created-y.created);head("📕 "+v.title,"章を選択");app.innerHTML=a.map(x=>`<div class=card><div onclick="openChapter('${x.id}')"><h3>📄 ${esc(x.title)}</h3><span class=muted>${x.text.length.toLocaleString()}文字</span></div><div class=row style="margin-top:10px"><button class=secondary onclick="editChapter('${x.id}')">✏️ 編集</button><button class=danger onclick="deleteChapter('${x.id}')">🗑️ 削除</button></div></div>`).join("")||"<div class=card>まだ章がありません。</div>";app.innerHTML+=`<div class=card><div class=row><button onclick=chapterForm()>＋ 章追加</button><button class=secondary onclick="$('#txt').click()">TXT読込</button></div><br><button class=danger onclick=deleteVolume()>この巻を削除</button></div>`}
window.openChapter=async i=>{S.v="reader";S.chapter=i;await render();let c=await get("chapters",i);setTimeout(()=>scrollTo(0,c.scroll||0),50)}
async function reader(){let c=await get("chapters",S.chapter),v=await get("volumes",c.volume);head("📖 "+c.title,v.title);app.innerHTML=`<article id=read class=reader>${esc(c.text)}</article>`;$("#read").style.fontSize=(localStorage.font||18)+"px"}
let timer;addEventListener("scroll",()=>{if(S.v!=="reader")return;clearTimeout(timer);timer=setTimeout(async()=>{let c=await get("chapters",S.chapter);c.scroll=scrollY;await put("chapters",c)},200)})
async function addBook(){let t=prompt("本のタイトル");if(t?.trim()){await put("books",{id:uid(),title:t.trim()});render()}}
async function addVolume(){let t=prompt("巻のタイトル");if(t?.trim()){await put("volumes",{id:uid(),book:S.book,title:t.trim()});render()}}
function chapterForm(x=null,text=""){S.v="form";head(x?"✏️ 章を編集":"＋ 章追加","本文を貼り付け");app.innerHTML=`<div class=card><input id=ct placeholder="章タイトル" value="${x?esc(x.title):""}"><textarea id=body placeholder="日本語本文">${esc(x?x.text:text)}</textarea><button id=save>保存</button></div>`;$("#save").onclick=async()=>{let t=$("#ct").value.trim(),b=$("#body").value;if(!t||!b.trim())return alert("タイトルと本文を入力してください");await put("chapters",x?{...x,title:t,text:b}:{id:uid(),volume:S.volume,title:t,text:b,created:Date.now(),scroll:0});S.v="chapters";render()}}
window.editChapter=async i=>chapterForm(await get("chapters",i));window.deleteChapter=async i=>{if(confirm("削除しますか？")){await del("chapters",i);render()}}
async function deleteVolume(){if(!confirm("巻と中の章を削除しますか？"))return;for(let c of await ix("chapters","volume",S.volume))await del("chapters",c.id);await del("volumes",S.volume);S.v="volumes";delete S.volume;render()}
async function deleteBook(){if(!confirm("本・巻・章をすべて削除しますか？"))return;for(let v of await ix("volumes","book",S.book)){for(let c of await ix("chapters","volume",v.id))await del("chapters",c.id);await del("volumes",v.id)}await del("books",S.book);S={v:"books"};render()}
$("#fab").onclick=()=>S.v==="books"?addBook():S.v==="volumes"?addVolume():chapterForm();$("#back").onclick=()=>{if(S.v==="volumes")S={v:"books"};else if(S.v==="chapters"){S.v="volumes";delete S.volume}else{S.v="chapters";delete S.chapter}render()}
$("#theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.dark=document.body.classList.contains("dark")?"1":"0"};if(localStorage.dark==="1")document.body.classList.add("dark");
function font(d){let n=Math.max(14,Math.min(30,Number(localStorage.font||18)+d));localStorage.font=n;if($("#read"))$("#read").style.fontSize=n+"px"}$("#minus").onclick=()=>font(-1);$("#plus").onclick=()=>font(1);
async function adj(d){let c=await get("chapters",S.chapter),a=(await ix("chapters","volume",c.volume)).sort((x,y)=>x.created-y.created),i=a.findIndex(x=>x.id===c.id);if(a[i+d])openChapter(a[i+d].id)}$("#prev").onclick=()=>adj(-1);$("#next").onclick=()=>adj(1);
$("#txt").onchange=async e=>{let f=e.target.files[0];if(f){chapterForm(null,await f.text());$("#ct").value=f.name.replace(/\.txt$/i,"");e.target.value=""}}
async function backup(){let d={books:await all("books"),volumes:await all("volumes"),chapters:await all("chapters")},b=new Blob([JSON.stringify(d)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="novel-reader-backup.json";a.click()}
$("#restore").onchange=async e=>{try{let d=JSON.parse(await e.target.files[0].text());if(!confirm("バックアップを追加しますか？"))return;for(let x of d.books)await put("books",x);for(let x of d.volumes)await put("volumes",x);for(let x of d.chapters)await put("chapters",x);render()}catch{alert("読み込めませんでした")}e.target.value=""}
openDB().then(render)